config/routes.rb
RedDevise1::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  post '/events/inquiry' => 'events#inquiry'

  get '/events/thankyou' => 'events#thankyou'
  get '/about' => 'home#about'

  resources :gears, :users, :events, :galleries, :links

  match 'auth/:provider/callback', to: 'sessions#create'
	# match 'auth/failure', to: redirect('/')
	match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#index'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :end_time, :start_time, :title

end

app/models/gear.rb
class Gear < ActiveRecord::Base
  attr_accessible :availability, :dayrate, :image, :name, :gear_type, :weekrate, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable 
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates_presence_of :email
  validates_uniqueness_of :email
  before_create :check_admin


  def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = (auth.info.nickname + "@twitter.com")
    user.name = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  private
  def check_admin
  	if self.email == "thrityfivestudio35@gmail.com" || self.email == "thirty5studio@twitter.com"
  		self.admin = true
  	else
  		self.admin = false
  	end
    true  #before commands cannot have its last return equal to false!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :is_admin, except: [:index, :show, :inquiry, :thankyou]
  
  def index
    @events = Event.all
  end

  def create
    new_event = Event.create(params[:event])
    redirect_to new_event
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes(params[:event])
    redirect_to "/events/#{event.id}"
  end

  def destroy
    Event.delete(params[:id])
    redirect_to events_path
  end

  def inquiry
    @user = current_user
    @name = params[:username]
    @title = params[:inquiry_titile]
    @reservation_type = params[:inquiry_type]
    @startdate = params[:startdate]
    @returndate = params[:returndate]
    @phone_num = params[:phone_number]
    @message = params[:comment]

    UserMailer.form_confirmation(@user, params).deliver
    UserMailer.admin_form_confirmation(@user, params).deliver
    redirect_to "/events/thankyou"

  end

  def thankyou
  end

  private
  def  is_admin
    if current_user == nil || !current_user.admin  
       redirect_to :root
    end
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

	def index
	end
	
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_filter :is_admin, except: [:index, :show]

  def index
    @gears = Gear.all
    render :index
  end

  def create
    new_gear = Gear.create(params[:gear])
    redirect_to new_gear
  end

  def new
    @gear = Gear.new
  end

  def edit
    @gear = Gear.find(params[:id])
  end

  def show
    @gear = Gear.find(params[:id])
  end

  def update
    gear = Gear.find(params[:id])
    gear.update_attributes(params[:gear])
    redirect_to "/gears/#{gear.id}"
  end

  def destroy
    Gear.delete(params[:id])
    redirect_to gears_path
  end

  private
    def  is_admin
      if current_user == nil || !current_user.admin  
         redirect_to :root
      end
    end
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	def index
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    #user = User.from_omniauth(raise request.env["omniauth.auth"].to_yaml)
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		# raise env["omniauth.auth"].to_yaml
	  user = User.from_omniauth(env["omniauth.auth"])
	  session[:user_id] = user.id
	  redirect_to root_url, notice: "Signed in!"
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "Signed out!"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def is_active?(link_path)
		if current_page?(link_path)
			"active"
		else
			""
		end
	end



end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
# require 'rubygems'
# require 'google/api_client'
# require 'yaml'

# oauth_yaml = YAML.load_file('app/helpers/google.yml')

# client = Google::APIClient.new
# client.authorization.client_id = oauth_yaml["client_id"]
# client.authorization.client_secret = oauth_yaml["client_secret"]
# client.authorization.scope = oauth_yaml["scope"]
# client.authorization.refresh_token = oauth_yaml["refresh_token"]
# client.authorization.access_token = oauth_yaml["access_token"]

# if client.authorization.refresh_token && client.authorization.expired?
#   client.authorization.fetch_access_token!
# end

# service = client.discovered_api('calendar', 'v3')

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/events/_event.html.erb
<div>
	<h3><%= event.title %></h3>
</div>

<div>
	<h3><%= event.start_time %></h3>
</div>

<div>
	<h3><%= event.end_time %></h3>
</div>

<div>
	<h3><%= event.description %></h3>
</div>

<% if current_user && current_user.admin  %>
	<%= link_to "Edit", edit_event_path(event) %>
<% end %>

<% if current_user && current_user.admin  %>
	<%= link_to "Delete", event_path(event), method: :delete %>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

	<li>Item(s) being rented: <%= f.text_field :title %></li>
	<li>Rental Begins: <%= f.text_field :start_time %></li>
	<li>Rental Ends: <%= f.text_field :end_time %></li>
	<li>Description: <%= f.text_area :description, size: "50x10" %></li>
	<li><%= f.submit %></li>

	<% end %>

app/views/events/edit.html.erb
<div class="bookings_container">
	<%= render 'form' %>
</div>

app/views/events/index.html.erb
<!--  old code for simple calendar https://github.com/excid3/simple_calendar#views
<% if current_user && current_user.admin== true %>
	<%= link_to "Add new booking", new_event_path %>
<% end %>

<% @events.each do |x| %>
	<% render "event", event: x %>
<% end %>

<div class="calendar">
<%=	@events.inspect %>
<%= calendar @events, {:prev_text=>" <<_   ", :next_text=>"   _>>"} do |event| %>
  <div><%= link_to event.title, event %></div>
<% end %>
</div>

-->
<div class="bookings_container">
<!-- if admin is logged in, show google calendar of bookings -->

<% if current_user && current_user.admin== true %>
<div class="google_calendar">

	<iframe src="https://www.google.com/calendar/embed?title=Thrity5studio&amp;showPrint=0&amp;showCalendars=0&amp;height=300&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=thirtyfivestudio35%40gmail.com&amp;color=%232F6309&amp;ctz=America%2FLos_Angeles" style=" border-width:0 " width="400" height="300" frameborder="0" scrolling="no"></iframe>
  <br>
  <br>
  <br>
</div>

<!-- if user is logged in, allow them to submit a inquery request -->

<% elsif current_user %>

   <!-- <%= form_tag "/events/inquiry", method: "post" %> -->

  <form action="/events/inquiry" method="post">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  	<li>By: <%= current_user.email %> </li><br>
  	<li>Full name:<br> <input type="text" name="username"></li><br>
  	<li>Title:<br> <input type="text" name="inquiry_titile"></li>
 		<div class="reservations">
 			<br> <input id="reservation" type="radio" name="inquiry_type" value="Reservation Request"> Reservation Request <br>
  		<input id="general" type="radio" name="inquiry_type" value="General Inquiry"> General Inquiry <br><br>
 			<ul class="reserve">
 			</ul>
 		</div>
  	<li>Please enter a phone number we can reach you at: <br><input type="text" name="phone_number"></li><br>
  	<li>Your comment:<br><textarea name="comment" row="8" cols="50"></textarea></li><br>
  	<li><input type="submit" value="submit"></li>
  	<br>
  	<br>

  </form>

<% else %>
Please <%= link_to "Sign In", new_user_session_path, :method => :post %> to submit a new request.

<% end %>
</div>

app/views/events/new.html.erb
<div class="bookings_container">
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="bookings_container">
	<%= render 'event', event: @event %>
	<%= @event.inspect %>
</div>

app/views/events/thankyou.html.erb
<div class="bookings_container">
Thankyou for submitting your request.  We will be in touch shortly.<br>

<%= link_to "Back to browsing equipment", gears_path, :method => :get %>
</div>

app/views/galleries/index.html.erb
<div class="portfolioFilter">

    <a href="#" data-filter="*" class="current">All Categories</a>
    <a href="#" data-filter=".camera_body">Camera Body</a>
    <a href="#" data-filter=".lenses">Lenses</a>
    <a href="#" data-filter=".package">Package</a>
    <a href="#" data-filter=".red">Red</a>
    <a href="#" data-filter=".demo">Demo</a>

</div>

<div class="portfolioContainer">

    <div class="red camera_body package">
        <img src="../assets/1.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/2.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/3.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/4.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/5.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/6.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package demo">
        <img src="../assets/7.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package demo">
        <img src="../assets/8.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="./../assets/9.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package demo">
        <img src="../assets/10.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/11.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body ">
        <img src="../assets/12.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/13.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/14.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/15.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package ">
        <img src="../assets/16.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/17.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/18.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/19.jpg" alt="image" height="250px" width="300px" />
    </div>

    <div class="red camera_body package">
        <img src="../assets/20.jpg" alt="image" height="250px" width="300px" />
    </div>



</div>





<!-- <div class="gallery_container">

<img id="homepage_image" src="../assets/<%= (1..20).to_a.sample.to_s %>.jpg" height="250px" width="auto" />

<div id="carousel-example-generic" class="carousel slide">
  <!-- Indicators -->
<!--   <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol> -->

  <!-- Wrapper for slides -->
<!--   <div class="carousel-inner">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">

      </div>
    </div>

  </div> -->

  <!-- Controls -->
<!--   <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="icon-next"></span>
  </a>

<script>
  $(document).ready(function(){
      $('.carousel').carousel({
      	interval: 3000;
      });
  });
  </script>


</div>

</div>  -->

app/views/gears/_form.html.erb
<%= form_for @gear do |f| %>

	<li>Equipment name: </li>
	<li><%= f.text_field :name %></li><br>
	<li>Equipment type: </li>
	<li><%= f.text_field :gear_type %></li><br>
	<li>Image of Equipment: </li>
	<li><%= f.text_field :image %></li><br>
	<li>Description: </li>
	<li><%= f.text_area :description, size: "50x10" %></li><br>
	<li>Day Rate: </li>
	<li><%= f.text_field :dayrate %></li><br>
	<li>Week Rate: </li>
	<li><%= f.text_field :weekrate %></li><br>
	<li><%= f.submit %></li>
	<br>
	<br>

	<% end %>

app/views/gears/_gear.html.erb
<div class="gear_bold">
	<h3><%= gear.name %></h3>
</div>


<div class="gear_small">
	<p><img src="<%= gear.image %>" alt="gear.name" height="150px" width="auto"></p>
</div>

<div class="gear_small">
	<p>Description: <p>
		<p><%= gear.description %></p>
</div>

<!-- <div class="gear_small">
	<p><%= gear.dayrate %></p>
</div>

<div class="gear_small">
	<p><%= gear.weekrate %></p>
</div> -->
<br>
<br>

	
<% if current_user && current_user.admin  %>
	<%= link_to "Edit", edit_gear_path(gear) %>
<% end %>

<% if current_user && current_user.admin  %>
	<%= link_to "Delete", gear_path(gear), method: :delete %>
<% end %>

app/views/gears/edit.html.erb
<div class="gear_container">
	<%= render 'form' %>
</div>

app/views/gears/index.html.erb
<div class="gear_container">

<% if current_user && current_user.admin== true %>

	<%= link_to "Add new gear", new_gear_path %>
	<br>
	<br>

<% end %>



<% @gears.each do |gear| %>

	<li><a href="/gears/<%= gear.id%>"><%= gear.name %></a></li>

<% end %>

</div>

app/views/gears/new.html.erb
<div class="gear_container">
	<%= render 'form' %>
</div>

app/views/gears/show.html.erb
<div class="gear_container">
	<%= render 'gear', gear: @gear %>
</div>

app/views/home/about.html.erb
<p class="intro">

	Welcome to Thirtyfivestudio, located in San Francisco, CA.  We have a RED Epic digital cinema camera package for rent.  Rental pickup by appointments only.  Please <%= link_to "Sign In", new_user_session_path, :method => :post %> with your account to submit reservation request, or call us at (949)413-2092.  

</p>

app/views/home/index.html.erb
<div class="homepage">
	
	<img id="homepage_image" src="<%= asset_path('5.jpg') %>" height="500px" width="auto" />

	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedDevise1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">

<!--devise div for sign_in/sign_out-->

	<div class="user_signin" >

				<% if user_signed_in? %>
				<ul class="user_signed_in">
					<% if current_user.admin == true %>
						<li>Signed in as admin using <%=current_user.email%></li>
					<% else %>
						<li>Signed in as <%= current_user.email %></li>
					<% end %>

					<li>  Not you? &nbsp <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>

				<% else %>
				<ul class="breadcrumb">
					<li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign up", new_user_registration_path, :method => :get %></button></li>
					<li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign In", new_user_session_path, :method => :post %></button></li>
					<li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></button></li>
					<!-- <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Continue as Guest", gears_path, :method => :get %></button></li> -->
				</ul>
				<% end %>

				<ul class="user_status">
					<li><p class="notice"><%= notice %></p></li>
			  	<li><p class="alert"><%= alert %></p></li>
		  	</ul>

	</div>
<!-- end devise div -->
<h1>thirty<span class="darkgrey bolder">5tudio</span>
	<span class="tagline">Camera Crew /
		<span class="darkgrey"> RED Cinema & Lens packages</span>
</h1>


<div id="page_nav" class="nav nav-tabs navbar-inverse">
	<p>
		<li class="<%=is_active?("/about")%>"><a href="/about"> Info </a></li>
		<li class="<%=is_active?("/gears")%>"><a href="/gears"> Equipment </a></li>
		<li class="<%=is_active?("/events")%>"><a href="/events"> Bookings </a> </li>
		<li class="<%=is_active?("/galleries")%>"><a href="/galleries"> Gallery </a></li>
		<li class="<%=is_active?("/links")%>"><a href="/links"> Stuff & Nonesense </a></li>
		<li class="<%=is_active?("/")%>"><a href="/"> Home </a> </li>

	</p>
</div>

<%= yield %>
<div class="push"></div>
</div>


</body>
	<div class="footer">
		<p>thrity5tudio &copy;  2013</p>
	</div>


</html>

app/views/links/index.html.erb
<div class="link_container">

	<img src="http://trailers.apple.com/trailers/independent/bansheechapter/images/background.jpg" height="200px" width="auto">
	<br>
	<br>
	<br>

	<iframe width="640" height="360" src="//www.youtube.com/embed/FvakUNt8Vhk?rel=0" frameborder="0" allowfullscreen></iframe>

	<li id="share-facebook"><a href="http://www.facebook.com/share.php?u=http://trailers.apple.com/trailers/independent/bansheechapter" target="_block" title="Share this on Facebook">Facebook</a></li>
	<li id="share-twitter"><a href="http://twitter.com/home?status=Banshee Chapter - See the trailer http://trailers.apple.com/trailers/independent/bansheechapter/" target="_block" title="Share this on Twitter">Twitter</a></li>

</div>